news_portal/news/urls.py
from django.urls import path
from .views import PostsList, SearchList, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, CategorySubscribeView, subscribe_category


urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам у нас останется пустым, позже станет ясно, почему
    path('', PostsList.as_view(), name='news'),
    path('search/', SearchList.as_view()),
    # т. к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого вызываем метод as_view
    # path('<int:pk>', PostDetail.as_view()),  # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),  # Ссылка на детали публикации
    path('create/', PostCreateView.as_view(), name='post_create'),  # Ссылка на создание публикации
    path('create/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDeleteView.as_view(), name='post_delete'),

    path('category/', CategorySubscribeView.as_view()),
    path('category/<int:pk>', subscribe_category, name='subscribe_category'),

]










# urlpatterns = [
#     path('category/', CategorySubscribe.as_view(), name='post_category'),
#     path('category/<int:pk>', subscribe_category, name='subscribe_category'),
#     path('category/<int:pk>', unsubscribe_category, name='unsubscribe_category'),
# ]
# , name='post_category'

news_portal/news_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),

    # делаем так, чтобы все адреса из нашего приложения (news/urls.py) сами автоматически подключались когда мы их добавим.
]



# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('appointments/', include(('appointments.urls', 'appointments'), namespace='appointments')),
#     path('accounts/', include('allauth.urls')),
# ]

news_portal/news/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


# Модель Author
class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.SmallIntegerField("рейтинг автора", default=0)

    def __str__(self):
        # return self.commentPost.author.authorUser.username  # получить имя автора поста
        return f'{self.authorUser.username}'

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.authorRating = pRat * 3 + cRat
        self.save()


# Модель Category
class Category(models.Model):
    categoryName = models.CharField('Выберите категорию публикаций для подписки:', max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='subscriber', blank=True)

    def __str__(self):
        return f'{self.categoryName}'


# Модель Post
class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORIES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    ]
    categoryType = models.CharField(max_length=2,
                                     choices=CATEGORIES,
                                     default=ARTICLE)
    pubDate = models.DateTimeField('Publication date ', auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='postCategory')
    postTitle = models.CharField('Title ', max_length=128)
    postText = models.TextField('Text')
    rating = models.SmallIntegerField("рейтинг статьи/новости", default=0)
    isUpdated = models.BooleanField(default=False)

    # Методы like() и dislike() в модели Post, которые увеличивают/уменьшают рейтинг на единицу.
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    # Метод preview() модели Post, который возвращает начало статьи (предварительный просмотр)
    # длиной 124 символа и добавляет многоточие в конце.
    def preview(self):
        return f'{self.postText[:124]} ...'

    def __str__(self):
        # получить название поста
        return f'{self.postTitle}. {self.postText[:124]} ...'

    def get_category(self):
        return f'{self.postCategory}'


    def get_absolute_url(self):
        return f'http://127.0.0.1:8000/news/{self.id}'
        # return f'/news/{self.id}'

    def message_subscriber(self):
        return f'Новая статья - "{self.postTitle}" в разделе "{self.postCategory.first()}" '

# Модель PostCategory
# Промежуточная модель для связи «многие ко многим»:
class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        # получить название поста
        return f'{self.postThrough}. {self.categoryThrough}'


# Модель Comment
class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    commentText = models.CharField('текст комментария', max_length=200)
    pubDate = models.DateTimeField('дата и время публикации комментария', auto_now_add=True)
    rating = models.SmallIntegerField("рейтинг комментария", default=0)

    # Метод __str__ выводит фамилию автора комментария
    def __str__(self):
        # return self.commentPost.author.authorUser.username  # получить имя автора поста
        return f'{self.commentUser.username}'

    # Методы like() и dislike() в модели Comment, которые увеличивают/уменьшают рейтинг на единицу.
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news_portal/news/forms.py
from django import forms
from django.forms import ModelForm, BooleanField  # Импортируем true-false поле
from .models import Post, Category, PostCategory


# Создаём модельную форму
class PostForm(ModelForm):
    check_box = BooleanField(label='Подтвердить!')  # добавляем галочку, или же true-false поле

    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.
    class Meta:
        model = Post
        fields = ['author', 'postTitle', 'postCategory', 'postText', 'categoryType',
                  'check_box']  # не забываем включить галочку в поля иначе она не будет показываться


# Создаём модельную форму
# class CategoryForm(ModelForm):
#
#     class Meta:
#         model = Category
#
#         fields = {
#             'categoryName': ['exact'],  # по названию категории (выбор из существуещего списка)
#         }

news_portal/news/views.py
from django.http import HttpResponse
from django.views import View

from .tasks import subscribe_category_confirmation_message

from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models.signals import ModelSignal
from django.shortcuts import render, redirect
from django.template.defaultfilters import truncatechars
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
# импортируем класс ListView, который говорит нам о том, что в этом представлении мы будем выводить список объектов из БД
# импортируем класс DetailView получения деталей объекта
from django.core.paginator import Paginator  # импортируем класс, позволяющий удобно осуществлять постраничный вывод
from django.contrib.auth.models import User
from datetime import datetime

from .models import Author, Category, Post, PostCategory, Comment
from .filters import PostFilter   # импортируем недавно написанный фильтр
from .forms import PostForm  # импортируем нашу форму

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from django.contrib.auth.mixins import PermissionRequiredMixin

# custom_create_signal = ModelSignal(use_caching=True)

# дженерик для редактирования объекта
class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'news/post_create.html'
    permission_required = ('news.change_post',)
    form_class = PostForm

    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте, который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        post = Post.objects.get(pk=id)
        post.isUpdated = True
        return post

    def form_valid(self, form):
        self.object = form.save()  # вызван save() значит отправляется сигнал без категории
        cat = Category.objects.get(pk=self.request.POST['postCategory'])
        self.object.postCategory.add(cat)  # добавляем категорию
        return super().form_valid(form)  # у родителя еще раз вызывается метод save(), вторая отправка сигнала.


class PostsList(ListView):
    model = Post  # указываем модель, объекты которой мы будем выводить
    template_name = 'news.html'  # указываем имя шаблона, в котором будет лежать HTML, в котором будут все инструкции о том, как именно пользователю должны вывестись наши объекты
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты, его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    ordering = ['-pubDate']  # вывод списка публикаций в обратном порядке, от более новых к более старым
    paginate_by = 10  # поставим постраничный вывод в один элемент


    # метод get_context_data нужен нам для того, чтобы мы могли передать переменные в шаблон. В возвращаемом словаре context будут храниться все переменные. Ключи этого словаря и есть переменные, к которым мы сможем потом обратиться через шаблон
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()  # добавим переменную текущей даты time_now
        context['news_list'] = Post.objects.all()  # добавим переменную всего списка публикаций, не подверженного эффекту пагинации
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context



# дженерик для получения деталей о товаре
class PostDetailView(DetailView):
    template_name = 'news/post_detail.html'
    queryset = Post.objects.all()


# дженерик для создания объекта. Надо указать только имя шаблона и класс формы, который мы написали в прошлом юните. Остальное он сделает за вас
class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news/post_create.html'
    permission_required = ('news.add_post',)
    form_class = PostForm  # добавляем форм класс, чтобы получать доступ к форме через метод POST

    def form_valid(self, form):
        self.object = form.save()  # вызван save() значит отправляется сигнал без категории
        cat = Category.objects.get(pk=self.request.POST['postCategory'])
        self.object.postCategory.add(cat)  # добавляем категорию
        return super().form_valid(form)  # у родителя еще раз вызывается метод save(), вторая отправка сигнала.


    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     # self.object.author = Author.objects.get(authorUsername=self.request.user)
    #     self.object.save()
    #
    #     cat = Category.objects.get(pk=self.request.POST['category'])
    #     self.object.postCategory.add(cat)
    #     custom_create_signal.send(sender=Post, instance=self.object, created=True, request=self.request)
    #
    #     validated = super().form_valid(form)
    #     return validated

# дженерик для удаления поста
class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news/post_delete.html'
    permission_required = ('news.delete_post',)
    queryset = Post.objects.all()
    success_url = '/news/'


class SearchList(ListView):
    model = Post
    template_name = 'news/news_search.html'
    context_object_name = 'news'
    ordering = ['-pubDate']
    paginate_by = 10  # поставим постраничный вывод в 10 элементов

    def get_filter(self):
        return PostFilter(self.request.GET, queryset=super().get_queryset())

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()  # добавим переменную текущей даты time_now
        context['news_list'] = Post.objects.all()  # добавим переменную всего списка публикаций, не подверженного эффекту пагинации
        context['filter'] = self.get_filter()
        context['categories'] = Category.objects.all()
        return context


class CategorySubscribeView(ListView):
    model = Category
    template_name = 'news/post_category.html'
    context_object_name = 'post_category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@login_required
def subscribe_category(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)
    id_u = request.user.id
    email = category.subscribers.get(id=id_u).email
    user_name = request.user.username
    category_name = Category.objects.get(id=pk).categoryName
    
    subscribe_category_confirmation_message.delay(user_name, email, category_name)
    
#     send_mail(
#         subject=f'News Portal: подписка на обновления категории {category}',
#         message=f'«{request.user}», вы подписались на обновление категории: «{category}».',
#         from_email='example@yandex.ru',
#         recipient_list=[f'{email}', ],
#     )
    return redirect('/news')

news_portal/templates/news/news_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% load custom_tags %}


{% get_filter_params request as params %}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Поиск новостей</h1>
    {{ time_now|date:'d M Y' }} <!-- Здесь мы применяем фильтр date. Он очень похож на метод strftime у даты. С его помощью мы можем выводить дату в нужном нам формате -->
    <h4> Количество всех публикаций: {{ news_list|length }} </h4>
    <hr>

<!-- Перед таблицей добавим форму для поиска -->
<br>
<form method="GET">
    {{ filter.form.as_p }} <!-- Форму от фильтров за нас сделает django. А вот кнопку, увы придётся делать самому -->
    <input type="submit" value="Search">
    <button> <a class="nav-link" href="/news/search/">Reset</a> </button>
</form>
<br>
    {% if news %}
        <table>
            <tr>
                <td>
                    <h4>Заголовок</h4>
                </td>
                <td>
                    <h4>Дата публикации</h4>
                </td>
                <td>
                    <h4>Текст</h4>
                </td>
            </tr>
        {% for new in news %}
            <tr>
                <td>
                    <a href="{{ new.get_absolute_url }}">{{ new.postTitle|censor }} </a>
                </td>
                <td>
                    {{ new.pubDate|date:'d M Y' }}
                </td>
                <td>
                    {{ new.postText|truncatechars:50|censor }}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <h2>Новостей и публикаций нет!</h2>
    {% endif %}
<br>
<br>
<!-- Проверяем что поддерживается постраничный вывод -->
{% if is_paginated %}

    <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
    {% if page_obj.has_previous %}
        <a href="?{% for param in params %}{{ param }}{% endfor %}&page=1">First</a>
        <a href="?{% for param in params %}{{ param }}{% endfor %}&page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?{% for param in params %}{{ param }}{% endfor %}&page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
    {% if page_obj.has_next %}
        <a href="?{% for param in params %}{{ param }}{% endfor %}&page={{ page_obj.next_page_number }}">>>></a>
        <a href="?{% for param in params %}{{ param }}{% endfor %}&page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
<br>
<br>
<br>
<br>
<button> <a class="nav-link" href="/news/category/">Подписаться на рассылку</a> </button>
<br>
<br>
<br>
<br>
{% endblock content %}

news_portal/templates/news/post_category.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% load crispy_forms_tags %}
 
{% block title %} Category {% endblock title %}
 
{% block content %}
<br>
<br>
<h3>Выберите категорию для подписки на новые публикации</h3>
<hr>
<br>
<table>
    {% for category in post_category %}
    <tr>
        <td>
            <h4><a href="{% url 'subscribe_category' category.id %}">{{ category.categoryName }} </a></h4>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

news_portal/templates/news/post_create.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% load crispy_forms_tags %}
 
{% block title %} News {% endblock title %}
 
{% block content %}
<br>
<h3>Создание/редактирование публикации</h3>
<hr>
<form method="POST">
    {% csrf_token %} 
    {{ form|crispy }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Опубликовать">
</form>
<br>
<br>
{% endblock content %}

news_portal/templates/news/post_delete.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% block title %} News {% endblock title %}

{% block content %}
<h2>Вы действительно хотите удалить данную публикацию?</h2>
<hr>
<br>
<table>
    <tr>
        <tr><h3>
            {{ post.postTitle|censor }}
        </h3></tr>
        <tr><p><i>
            {{ post.pubDate|date:'d M Y H:i' }}
        </i></p></tr>
        <tr><p><i>
            {{ post.author }}
        </i></p></tr>
        <tr>
            {{ post.postText|censor }}
        </tr>
    </tr>
</table>

<br>
<hr>
<br>

<form method="POST">
    {% csrf_token %}
    <p>Подтвердить <input type="checkbox" name="Подтвердить" required="required"></p>
    <input type="submit" value="удалить">
</form>
{% endblock content %}

news_portal/templates/news/post_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>{{ post.get_categoryType_display }}</h1>
<!--    {{ time_now|date:'d M Y' }} &lt;!&ndash; Здесь мы применяем фильтр date. Он очень похож на метод strftime у даты. С его помощью мы можем выводить дату в нужном нам формате &ndash;&gt;-->
    <hr>
    {% if post %}
        <table>
            <tr>
                <tr><h3>
                    {{ post.postTitle|censor }}
                </h3></tr>
                <tr><p><i>
                    {{ post.pubDate|date:'d M Y H:i' }}
                </i></p></tr>
                <tr><p><i>
                    {{ post.author }}
                </i></p></tr>
                <tr>
                    {{ post.postText|censor }}
                </tr>
            </tr>
        </table>
    {% else %}
        <h2>Новостей и публикаций нет!</h2>
    {% endif %}
<br>
<hr>
<br>
<button> <a class="nav-link" href="/news/">Вернуться</a> </button>

{% endblock content %}

news_portal/templates/news/subscription.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- не забываем заранее загружать наши фильтры! -->

{% load crispy_forms_tags %}
 
{% block title %} Category {% endblock title %}
 
{% block content %}
<br>
<br>
<h3>Оформить подписку на публикации</h3>
<hr>

<p class="editContent"> By subscribing to our mailing list you will always
    get latest news and updates from us.</p>
<br>
<br>
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <br>
    <br>
    <input type="submit" value="Подписаться">
</form>
{% endblock content %}